services:
  api:
    build: ./
    container_name: lfa-backend
    restart: always
    networks:
      - webnet
    ports:
      - '3005:3005'
    env_file:
      - .env

networks:
  webnet:
    driver: bridge